//! The order a [`drive_with`](super::drive_with) run takes.
//!
//! At every step the runner has a list of ready actions, oldest first — an
//! effect for the handler (only each machine's oldest, so its effects stay in
//! order), a queued reply, a machine to resume — and asks its schedule which
//! to take, whether to resume some machine spuriously first, and whether to
//! kill one. [`Fifo`] is the plain order. [`Choices`] takes its decisions from
//! a stream of bytes, so a property test can feed it generated bytes and a
//! failure is reproduced by the same bytes.

/// How a run picks its next step.
pub trait Schedule {
    /// Which of `ready` actions to take next, `0` being the oldest. Values of
    /// `ready` or more are clamped to the newest.
    fn next(&mut self, ready: usize) -> usize;

    /// Whether to resume one of the `machines` spuriously before the next
    /// step, and which. A routine must treat that as harmless.
    fn stutter(&mut self, machines: usize) -> Option<usize>;

    /// Whether to kill one of the `machines` before the next step, and which:
    /// drop it, as a host's `free` or a panic would. Never, unless a schedule
    /// says otherwise.
    fn kill(&mut self, _machines: usize) -> Option<usize> {
        None
    }
}

/// Oldest first, and never a spurious resume: effects in the order they were
/// recorded, replies as they were queued.
#[derive(Clone, Copy, Debug, Default)]
pub struct Fifo;

impl Schedule for Fifo {
    fn next(&mut self, _: usize) -> usize {
        0
    }

    fn stutter(&mut self, _: usize) -> Option<usize> {
        None
    }
}

/// Decisions read from `choices`, one byte each: which ready action (the
/// byte modulo their number) and, before it, whether to stutter (one byte in
/// eight, then another naming the machine). Once the bytes run out it is
/// [`Fifo`].
///
/// It kills nothing unless made [`crashing`](Self::crashing), so the same
/// bytes give the same run either way until the first kill.
#[derive(Clone, Debug)]
pub struct Choices<I> {
    choices: I,
    crashing: bool,
}

impl<I: Iterator<Item = u8>> Choices<I> {
    /// A schedule reading its decisions from `choices`.
    pub const fn new(choices: I) -> Self {
        Self {
            choices,
            crashing: false,
        }
    }

    /// Also decide, before each step, whether to kill a machine: one byte in
    /// sixteen, then another naming it.
    #[must_use]
    pub const fn crashing(mut self) -> Self {
        self.crashing = true;
        self
    }
}

impl<I: Iterator<Item = u8>> Schedule for Choices<I> {
    fn next(&mut self, ready: usize) -> usize {
        self.choices
            .next()
            .map_or(0, |b| usize::from(b) % ready.max(1))
    }

    fn stutter(&mut self, machines: usize) -> Option<usize> {
        self.one_in(8, machines)
    }

    fn kill(&mut self, machines: usize) -> Option<usize> {
        if self.crashing {
            self.one_in(16, machines)
        } else {
            None
        }
    }
}

impl<I: Iterator<Item = u8>> Choices<I> {
    /// One byte: whether, one time in `odds`; then another: which of
    /// `machines`.
    fn one_in(&mut self, odds: u8, machines: usize) -> Option<usize> {
        match self.choices.next() {
            Some(b) if b % odds == 0 && machines > 0 => {
                self.choices.next().map(|m| usize::from(m) % machines)
            }
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fifo_takes_the_oldest_and_never_stutters_or_kills() {
        assert_eq!(
            (Fifo.next(3), Fifo.stutter(3), Fifo.kill(3)),
            (0, None, None)
        );
    }

    #[test]
    fn a_choice_is_its_byte_modulo_the_ready_count_then_fifo() {
        let mut choices = Choices::new([5_u8].into_iter());
        assert_eq!(choices.next(3), 2);
        assert_eq!(choices.next(3), 0, "out of bytes: the oldest");
    }

    #[test]
    fn one_byte_in_eight_stutters_and_the_next_names_the_machine() {
        assert_eq!(Choices::new([8_u8, 5].into_iter()).stutter(3), Some(2));
        assert_eq!(Choices::new([9_u8, 5].into_iter()).stutter(3), None);
        assert_eq!(
            Choices::new([8_u8, 5].into_iter()).stutter(0),
            None,
            "no machine to name"
        );
    }

    #[test]
    fn only_a_crashing_schedule_kills_and_then_one_byte_in_sixteen() {
        let mut plain = Choices::new([16_u8, 5].into_iter());
        assert_eq!(plain.kill(3), None);
        assert_eq!(plain.next(256), 16, "deciding not to kill read no byte");

        assert_eq!(
            Choices::new([16_u8, 5].into_iter()).crashing().kill(3),
            Some(2)
        );
        assert_eq!(
            Choices::new([17_u8, 5].into_iter()).crashing().kill(3),
            None
        );
    }
}
