//! The order a [`drive_with`](super::drive_with) run takes.
//!
//! At every step the runner has a list of ready actions, oldest first — an
//! effect for the handler (only each machine's oldest, so its effects stay in
//! order), a queued reply, a machine to resume — and asks its schedule which
//! to take, whether to resume some machine spuriously first, and whether to
//! kill one. [`Fifo`] is the plain order. [`Choices`] takes its decisions from
//! a stream of bytes, so a property test can feed it generated bytes and a
//! failure is reproduced by the same bytes.

/// How a run picks its next step.
pub trait Schedule {
    /// Which of `ready` actions to take next, `0` being the oldest. Values of
    /// `ready` or more are clamped to the newest.
    fn next(&mut self, ready: usize) -> usize;

    /// Whether to resume one of the `machines` spuriously before the next
    /// step, and which. A routine must treat that as harmless.
    fn stutter(&mut self, machines: usize) -> Option<usize>;

    /// Whether to kill one of the `machines` before the next step, and which:
    /// drop it, as a host's `free` or a panic would. Never, unless a schedule
    /// says otherwise.
    fn kill(&mut self, _machines: usize) -> Option<usize> {
        None
    }
}

/// Oldest first, and never a spurious resume: effects in the order they were
/// recorded, replies as they were queued.
#[derive(Clone, Copy, Debug, Default)]
pub struct Fifo;

impl Schedule for Fifo {
    fn next(&mut self, _: usize) -> usize {
        0
    }

    fn stutter(&mut self, _: usize) -> Option<usize> {
        None
    }
}

/// Decisions read from `choices`, one byte each: which ready action (the
/// byte modulo their number) and, before it, whether to stutter (one byte in
/// eight, then another naming the machine). Once the bytes run out it is
/// [`Fifo`].
///
/// It kills nothing unless made [`crashing`](Self::crashing), so the same
/// bytes give the same run either way until the first kill.
#[derive(Clone, Debug)]
pub struct Choices<I> {
    choices: I,
    crashing: bool,
}

impl<I: Iterator<Item = u8>> Choices<I> {
    /// A schedule reading its decisions from `choices`.
    pub const fn new(choices: I) -> Self {
        Self {
            choices,
            crashing: false,
        }
    }

    /// Also decide, before each step, whether to kill a machine: one byte in
    /// sixteen, then another naming it.
    #[must_use]
    pub const fn crashing(mut self) -> Self {
        self.crashing = true;
        self
    }
}

impl<I: Iterator<Item = u8>> Schedule for Choices<I> {
    fn next(&mut self, ready: usize) -> usize {
        self.choices
            .next()
            .map_or(0, |b| usize::from(b) % ready.max(1))
    }

    fn stutter(&mut self, machines: usize) -> Option<usize> {
        self.one_in(8, machines)
    }

    fn kill(&mut self, machines: usize) -> Option<usize> {
        if self.crashing {
            self.one_in(16, machines)
        } else {
            None
        }
    }
}

impl<I: Iterator<Item = u8>> Choices<I> {
    /// One byte: whether, one time in `odds`; then another: which of
    /// `machines`.
    fn one_in(&mut self, odds: u8, machines: usize) -> Option<usize> {
        match self.choices.next() {
            Some(b) if b % odds == 0 && machines > 0 => {
                self.choices.next().map(|m| usize::from(m) % machines)
            }
            _ => None,
        }
    }
}
