//! The order a [`drive_with`](super::drive_with) run takes.
//!
//! At every step the runner has a list of ready actions, oldest first — an
//! effect for the handler (only each machine's oldest, so its effects stay in
//! order), a queued reply, a machine to resume — and asks its schedule which
//! to take, and whether to resume some machine spuriously
//! first. [`Fifo`] is the plain order. [`Choices`] takes its decisions from a
//! stream of bytes, so a property test can feed it generated bytes and a
//! failure is reproduced by the same bytes.

/// How a run picks its next step.
pub trait Schedule {
    /// Which of `ready` actions to take next, `0` being the oldest. Values of
    /// `ready` or more are clamped to the newest.
    fn next(&mut self, ready: usize) -> usize;

    /// Whether to resume one of the `machines` spuriously before the next
    /// step, and which. A routine must treat that as harmless.
    fn stutter(&mut self, machines: usize) -> Option<usize>;
}

/// Oldest first, and never a spurious resume: effects in the order they were
/// recorded, replies as they were queued.
#[derive(Clone, Copy, Debug, Default)]
pub struct Fifo;

impl Schedule for Fifo {
    fn next(&mut self, _: usize) -> usize {
        0
    }

    fn stutter(&mut self, _: usize) -> Option<usize> {
        None
    }
}

/// Decisions read from `choices`, one byte each: which ready action (the
/// byte modulo their number) and, before it, whether to stutter (one byte in
/// eight, then another naming the machine). Once the bytes run out it is
/// [`Fifo`].
#[derive(Clone, Debug)]
pub struct Choices<I> {
    choices: I,
}

impl<I: Iterator<Item = u8>> Choices<I> {
    /// A schedule reading its decisions from `choices`.
    pub const fn new(choices: I) -> Self {
        Self { choices }
    }
}

impl<I: Iterator<Item = u8>> Schedule for Choices<I> {
    fn next(&mut self, ready: usize) -> usize {
        self.choices
            .next()
            .map_or(0, |b| usize::from(b) % ready.max(1))
    }

    fn stutter(&mut self, machines: usize) -> Option<usize> {
        match self.choices.next() {
            Some(b) if b % 8 == 0 && machines > 0 => {
                self.choices.next().map(|m| usize::from(m) % machines)
            }
            _ => None,
        }
    }
}
