//! The host table against the host-protocol spec.
//!
//! `spec/host_protocol.qnt` models what `ABI.md` promises about calls, and the
//! model checker proves the protocol's properties over that model. This checks
//! the other half: that the table does what the model says. Every trace Quint
//! drew from the spec (`spec/traces/`, regenerated by `spec:traces`) is
//! replayed against the real table — the spec's programs run as real
//! routines, with real channels, asks, `select`, spawning, and panics — and
//! each call's output must be the spec's: the `woke` frames, the children
//! spawned, the ids asked and closed, and the status. So must what `wakes`
//! reports when the host is quiet.

use async_channel::{Receiver, Sender};
use sans_effort_core::{
    boundary::{
        codec::{Encode, Reader, Writer},
        host_effect::HostEffect,
        pending::Pending,
    },
    driver::{BoxedRoutine, outbox::Outbox, status::Status},
    reply::handle::ReplyHandle,
    select::select,
};
use sans_effort_host::{
    contract::{FRAME_ASK, FRAME_CLOSED, FRAME_TELL, FRAME_WOKE},
    error::Error,
    table,
};
use serde_json::Value;
use std::{
    collections::{BTreeSet, HashMap},
    sync::{Arc, Mutex, Once, PoisonError},
};
use testresult::TestResult;

// ---- The spec's instances --------------------------------------------------

/// One step of a routine: the spec's `Instr`.
#[derive(Clone, Copy, Debug)]
enum Instr {
    Send(&'static str),
    Recv(&'static str),
    Spawn(&'static str),
    Ask,
    Race(&'static str),
    Panic,
}

/// An instance's programs and the senders each holds, as in the spec. Hosts
/// that differ only in their own behaviour share an instance.
struct Instance {
    programs: &'static [(&'static str, &'static [Instr])],
    holds: &'static [(&'static str, &'static [&'static str])],
    channels: &'static [&'static str],
    root: &'static str,
}

impl Instance {
    fn program(&self, name: &str) -> Option<&'static [Instr]> {
        self.programs
            .iter()
            .find(|(n, _)| *n == name)
            .map(|(_, p)| *p)
    }

    fn holds(&self, name: &str) -> Result<&'static [&'static str], String> {
        self.holds
            .iter()
            .find(|(n, _)| *n == name)
            .map(|(_, h)| *h)
            .ok_or_else(|| format!("no program {name} in this instance"))
    }

    fn of(name: &str) -> Result<&'static Self, String> {
        match name {
            "ping_pong" | "ping_pong_sequential" | "mistaken_ignores_woke" => Ok(&PING_PONG),
            "deadline" | "mistaken_ignores_closed" => Ok(&DEADLINE),
            "panic_wakes" => Ok(&PANIC_WAKES),
            "deadlock" => Ok(&DEADLOCK),
            other => Err(format!(
                "no instance {other}: add it here as in spec/host_protocol.qnt"
            )),
        }
    }
}

const PING_PONG: Instance = Instance {
    programs: &[
        (
            "parent",
            &[
                Instr::Spawn("ponger"),
                Instr::Send("ping"),
                Instr::Recv("pong"),
                Instr::Send("ping"),
                Instr::Recv("pong"),
            ],
        ),
        (
            "ponger",
            &[
                Instr::Recv("ping"),
                Instr::Send("pong"),
                Instr::Recv("ping"),
                Instr::Send("pong"),
                Instr::Recv("ping"),
            ],
        ),
    ],
    holds: &[("parent", &["ping"]), ("ponger", &["pong"])],
    channels: &["ping", "pong"],
    root: "parent",
};

const DEADLINE: Instance = Instance {
    programs: &[
        (
            "parent",
            &[Instr::Spawn("quick"), Instr::Race("answer"), Instr::Ask],
        ),
        ("quick", &[Instr::Send("answer")]),
    ],
    holds: &[("parent", &[]), ("quick", &["answer"])],
    channels: &["answer"],
    root: "parent",
};

const PANIC_WAKES: Instance = Instance {
    programs: &[
        ("parent", &[Instr::Spawn("crasher"), Instr::Recv("signal")]),
        ("crasher", &[Instr::Panic]),
    ],
    holds: &[("parent", &[]), ("crasher", &["signal"])],
    channels: &["signal"],
    root: "parent",
};

const DEADLOCK: Instance = Instance {
    programs: &[
        (
            "parent",
            &[Instr::Spawn("other"), Instr::Recv("from_other")],
        ),
        ("other", &[Instr::Recv("from_parent")]),
    ],
    holds: &[("parent", &["from_parent"]), ("other", &["from_other"])],
    channels: &["from_parent", "from_other"],
    root: "parent",
};

// ---- The programs as real routines --------------------------------------

enum Effect {
    Ask(ReplyHandle<()>),
    Spawn(Box<dyn FnOnce(Outbox<Effect>) -> BoxedRoutine + Send>),
}

enum View {
    Ask(u64),
    Spawned(u64),
}

/// As a binding's vocabulary does: a spawned child is registered when the
/// call that spawned it is encoded.
impl HostEffect for Effect {
    type View = View;

    fn split(self) -> (View, Option<Pending>) {
        match self {
            Effect::Ask(reply) => (View::Ask(reply.id()), Some(Pending::Unit(reply))),
            Effect::Spawn(make) => (View::Spawned(table::new_boxed(make)), None),
        }
    }
}

impl Encode for View {
    fn encode(&self, w: &mut Writer) {
        let (tag, value) = match self {
            View::Ask(id) => (1, id),
            View::Spawned(handle) => (2, handle),
        };
        w.u8(tag);
        w.u64(*value);
    }
}

/// Senders a program holds, by channel.
type Held = Vec<(&'static str, Sender<()>)>;

/// One run's channels. The receivers are shared — any machine may receive on
/// any channel, as in the spec — and the senders each spawn will hand its
/// child wait in the kit until then. No other sender exists, so a channel
/// closes when its last holder ends, as the spec counts.
struct World {
    instance: &'static Instance,
    receivers: HashMap<&'static str, Receiver<()>>,
    kit: Mutex<HashMap<&'static str, Vec<Held>>>,
}

impl World {
    /// A world for `instance`, and the senders its root holds.
    fn new(instance: &'static Instance) -> Result<(Arc<Self>, Held), String> {
        let mut senders = HashMap::new();
        let mut receivers = HashMap::new();
        for &c in instance.channels {
            let (tx, rx) = async_channel::unbounded();
            senders.insert(c, tx);
            receivers.insert(c, rx);
        }
        let bundle = |program: &str| -> Result<Held, String> {
            instance
                .holds(program)?
                .iter()
                .map(|&c| {
                    let tx = senders.get(c).ok_or_else(|| format!("no channel {c}"))?;
                    Ok((c, tx.clone()))
                })
                .collect()
        };
        let root = bundle(instance.root)?;
        let mut kit: HashMap<&'static str, Vec<Held>> = HashMap::new();
        for (_, program) in instance.programs {
            for instr in *program {
                if let Instr::Spawn(child) = *instr {
                    kit.entry(child).or_default().push(bundle(child)?);
                }
            }
        }
        let world = Self {
            instance,
            receivers,
            kit: Mutex::new(kit),
        };
        Ok((Arc::new(world), root))
    }

    fn receiver(&self, c: &str) -> Option<&Receiver<()>> {
        self.receivers.get(c)
    }
}

/// The message a program's `Panic` panics with, silenced by `quiet_panics`.
const PANIC: &str = "a spec program panics, as it says";

/// A routine running `name`'s program, holding `held` until it ends.
#[expect(
    clippy::expect_used,
    clippy::panic,
    reason = "a routine cannot return an error: a broken fixture panics the machine, which the replay reports as a divergence, and a program's `Panic` panics on purpose"
)]
fn program(
    world: Arc<World>,
    name: &'static str,
    held: Held,
) -> impl FnOnce(Outbox<Effect>) -> BoxedRoutine + Send {
    move |outbox| {
        Box::pin(async move {
            let steps = world
                .instance
                .program(name)
                .expect("a program of this instance");
            for instr in steps {
                match *instr {
                    Instr::Send(c) => {
                        let (_, tx) = held
                            .iter()
                            .find(|(h, _)| *h == c)
                            .expect("a program sends only on channels it holds");
                        tx.try_send(()).expect("unbounded, and open while held");
                    }
                    Instr::Recv(c) => {
                        let rx = world.receiver(c).expect("a channel of this instance");
                        if rx.recv().await.is_err() {
                            return;
                        }
                    }
                    Instr::Spawn(child) => {
                        let senders = world
                            .kit
                            .lock()
                            .unwrap_or_else(PoisonError::into_inner)
                            .get_mut(child)
                            .and_then(Vec::pop)
                            .expect("a bundle for each spawn");
                        let make = program(Arc::clone(&world), child, senders);
                        outbox.tell(Effect::Spawn(Box::new(make)));
                    }
                    Instr::Ask => outbox.ask(Effect::Ask).await,
                    Instr::Race(c) => {
                        let rx = world.receiver(c).expect("a channel of this instance");
                        select(rx.recv(), outbox.ask(Effect::Ask)).await;
                    }
                    Instr::Panic => panic!("{PANIC}"),
                }
            }
        })
    }
}

/// Keep the programs' deliberate panics out of the output; leave every other
/// panic — a failed assertion — to the default hook.
fn quiet_panics() {
    static ONCE: Once = Once::new();
    ONCE.call_once(|| {
        let default = std::panic::take_hook();
        std::panic::set_hook(Box::new(move |info| {
            let ours = info
                .payload()
                .downcast_ref::<String>()
                .is_some_and(|s| s == PANIC);
            if !ours {
                default(info);
            }
        }));
    });
}

// ---- ITF ---------------------------------------------------------------------

/// A field of an ITF record or object; `Null` if there is none.
fn at<'a>(v: &'a Value, key: &str) -> &'a Value {
    v.get(key).unwrap_or(&Value::Null)
}

/// The two elements of an ITF pair (a map entry, a tuple).
fn pair(v: &Value) -> Result<(&Value, &Value), String> {
    match v.as_array().map(Vec::as_slice) {
        Some([first, second]) => Ok((first, second)),
        _ => Err(format!("an ITF pair: {v}")),
    }
}

fn int(v: &Value) -> Result<u64, String> {
    at(v, "#bigint")
        .as_str()
        .and_then(|s| s.parse().ok())
        .ok_or_else(|| format!("an ITF integer: {v}"))
}

fn set(v: &Value) -> Result<BTreeSet<u64>, String> {
    at(v, "#set")
        .as_array()
        .ok_or_else(|| format!("an ITF set: {v}"))?
        .iter()
        .map(int)
        .collect()
}

fn tag(v: &Value) -> Result<&str, String> {
    at(v, "tag")
        .as_str()
        .ok_or_else(|| format!("an ITF variant: {v}"))
}

/// An ITF `Option`'s value, which `what` says must be there.
fn some<'a>(v: &'a Value, what: &str) -> Result<&'a Value, String> {
    match tag(v)? {
        "Some" => Ok(at(v, "value")),
        _ => Err(format!("{what}: {v}")),
    }
}

/// The value at `key` in an ITF map, which `what` says must be there.
fn lookup<'a>(map: &'a Value, key: u64, what: &str) -> Result<&'a Value, String> {
    for entry in at(map, "#map")
        .as_array()
        .ok_or_else(|| format!("an ITF map: {map}"))?
    {
        let (k, v) = pair(entry)?;
        if int(k)? == key {
            return Ok(v);
        }
    }
    Err(format!("{what}: {key}"))
}

// ---- The replay ----------------------------------------------------------------

/// A call's output, in the spec's terms: machines by the spec's numbers.
#[derive(Debug, Default, PartialEq, Eq)]
struct Output {
    woke: BTreeSet<u64>,
    spawned: BTreeSet<u64>,
    asked: BTreeSet<u64>,
    closed: BTreeSet<u64>,
    status: String,
}

impl Output {
    fn from_spec(v: &Value) -> Result<Self, String> {
        Ok(Self {
            woke: set(at(v, "woke"))?,
            spawned: set(at(v, "spawned"))?,
            asked: set(at(v, "asked"))?,
            closed: set(at(v, "closed"))?,
            status: tag(at(v, "status"))?.to_owned(),
        })
    }
}

struct Replay {
    /// Real handles, by the spec's machine number.
    handles: Vec<u64>,
}

impl Replay {
    fn spec_number(&self, handle: u64) -> Result<u64, String> {
        let at = self
            .handles
            .iter()
            .position(|&h| h == handle)
            .ok_or_else(|| format!("handle {handle} names no machine of this run"))?;
        u64::try_from(at).map_err(|e| e.to_string())
    }

    fn real(&self, machine: u64) -> Result<u64, String> {
        usize::try_from(machine)
            .ok()
            .and_then(|at| self.handles.get(at))
            .copied()
            .ok_or_else(|| format!("machine {machine} has not been created"))
    }

    /// The output of a real call, in the spec's terms; children it spawned
    /// are numbered as the spec numbers them, in order.
    fn observe(&mut self, result: Result<(Vec<u8>, Status), Error>) -> Result<Output, String> {
        let (bytes, status) = match result {
            Ok(ok) => ok,
            // A panic removes the machine: the spec's `Gone`, nothing out.
            Err(Error::Panicked) => {
                return Ok(Output {
                    status: "Gone".into(),
                    ..Output::default()
                });
            }
            Err(e) => return Err(format!("the call failed: {e}")),
        };
        let mut out = Output {
            status: format!("{status:?}"),
            ..Output::default()
        };
        let mut frames = Reader::new(&bytes);
        while !frames.is_empty() {
            let kind = frames.u8().map_err(|e| e.to_string())?;
            let mut payload = Reader::new(frames.bytes().map_err(|e| e.to_string())?);
            match kind {
                FRAME_WOKE | FRAME_CLOSED => {
                    let value = payload.u64().map_err(|e| e.to_string())?;
                    if kind == FRAME_WOKE {
                        out.woke.insert(self.spec_number(value)?);
                    } else {
                        out.closed.insert(value);
                    }
                }
                FRAME_ASK | FRAME_TELL => {
                    let tag = payload.u8().map_err(|e| e.to_string())?;
                    let value = payload.u64().map_err(|e| e.to_string())?;
                    match (kind, tag) {
                        (FRAME_ASK, 1) => {
                            out.asked.insert(value);
                        }
                        (FRAME_TELL, 2) => {
                            out.spawned.insert(
                                u64::try_from(self.handles.len()).map_err(|e| e.to_string())?,
                            );
                            self.handles.push(value);
                        }
                        other => return Err(format!("an unknown record {other:?}")),
                    }
                }
                other => return Err(format!("an unknown frame kind {other}")),
            }
        }
        Ok(out)
    }

    /// The real `wakes`, as spec machine numbers.
    fn wakes(&self) -> Result<BTreeSet<u64>, String> {
        let bytes = table::wakes();
        let mut frames = Reader::new(&bytes);
        let mut woken = BTreeSet::new();
        while !frames.is_empty() {
            let _kind = frames.u8().map_err(|e| e.to_string())?;
            let handle = Reader::new(frames.bytes().map_err(|e| e.to_string())?)
                .u64()
                .map_err(|e| e.to_string())?;
            woken.insert(self.spec_number(handle)?);
        }
        Ok(woken)
    }
}

/// A unit reply record for request `id`: kind 3, the id, no payload.
fn unit_reply(id: u64) -> Vec<u8> {
    let mut w = Writer::new();
    w.u8(3);
    w.u64(id);
    w.finish()
}

/// Replay one trace; `Err` describes the first step where the table and the
/// spec disagree.
fn replay(instance: &'static Instance, trace: &[Value]) -> Result<usize, String> {
    let (world, root_senders) = World::new(instance)?;
    let root = table::new(program(Arc::clone(&world), instance.root, root_senders));
    let mut run = Replay {
        handles: vec![root],
    };
    let mut live: BTreeSet<u64> = BTreeSet::from([0]);
    let mut calls = 0;

    for (index, steps) in trace.windows(2).enumerate() {
        let [before, after] = steps else {
            unreachable!("windows of two");
        };
        let step = index + 1;
        let picks = at(after, "picks");
        let action = at(after, "action")
            .as_str()
            .ok_or_else(|| format!("step {step}: no action"))?;
        match action {
            "call" => {
                let event = some(at(picks, "e"), "a call picks an event")?;
                let (machine, result) = match tag(event)? {
                    "Resume" => {
                        let machine = int(at(event, "value"))?;
                        (machine, table::resume(run.real(machine)?))
                    }
                    "Reply" => {
                        let (machine, id) = pair(at(at(event, "value"), "#tup"))?;
                        let (machine, id) = (int(machine)?, int(id)?);
                        (machine, table::reply(run.real(machine)?, &unit_reply(id)))
                    }
                    other => return Err(format!("step {step}: an unknown event {other}")),
                };
                calls += 1;
                let expected = Output::from_spec(lookup(
                    at(after, "in_flight"),
                    machine,
                    "the call is in flight",
                )?)?;
                let stale = int(at(after, "stale"))? > int(at(before, "stale"))?;
                let actual = match result {
                    // A reply to a closed request, or to a machine gone: the
                    // spec delivers nothing, and the table refuses it.
                    Err(Error::Stale { .. } | Error::BadHandle) if stale => Output {
                        status: expected.status.clone(),
                        ..Output::default()
                    },
                    Err(Error::BadHandle) if expected.status == "Gone" => Output {
                        status: "Gone".into(),
                        ..Output::default()
                    },
                    result => run
                        .observe(result)
                        .map_err(|e| format!("step {step}: {e}"))?,
                };
                if actual != expected {
                    return Err(format!(
                        "step {step}, call on machine {machine}:\n  spec:  {expected:?}\n  table: {actual:?}"
                    ));
                }
                live.extend(actual.spawned.iter().copied());
                if actual.status == "Gone" {
                    live.remove(&machine);
                }
            }
            "ret" => {
                let machine = int(some(at(picks, "h"), "a return picks a machine")?)?;
                let out = Output::from_spec(lookup(
                    at(before, "in_flight"),
                    machine,
                    "the call was in flight",
                )?)?;
                if out.status == "Complete" {
                    table::free(run.real(machine)?)
                        .map_err(|e| format!("step {step}: freeing machine {machine}: {e}"))?;
                    live.remove(&machine);
                }
            }
            "quiet" => {
                let expected = set(at(before, "wakes"))?;
                let actual = run.wakes()?;
                if actual != expected {
                    return Err(format!(
                        "step {step}, wakes:\n  spec:  {expected:?}\n  table: {actual:?}"
                    ));
                }
            }
            "done" => {}
            other => return Err(format!("step {step}: an unknown action {other}")),
        }
    }

    // A stall leaves machines behind; the table is process-wide.
    for machine in live {
        table::free(run.real(machine)?).unwrap_or_default();
    }
    drop(table::wakes());
    Ok(calls)
}

#[test]
fn the_table_does_what_the_spec_says() -> TestResult {
    quiet_panics();
    let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/../spec/traces");
    let mut files = Vec::new();
    for entry in std::fs::read_dir(dir)? {
        let path = entry?.path();
        if path.extension().is_some_and(|e| e == "json") {
            files.push(path);
        }
    }
    files.sort();

    let (mut traces, mut calls) = (0, 0);
    for path in files {
        let file: Value = serde_json::from_str(&std::fs::read_to_string(&path)?)?;
        let name = at(&file, "instance")
            .as_str()
            .ok_or("a fixture names its instance")?;
        let instance = Instance::of(name)?;
        let drawn = at(&file, "traces")
            .as_array()
            .ok_or("a fixture holds traces")?;
        for (n, trace) in drawn.iter().enumerate() {
            let steps = trace.as_array().ok_or("a trace is a list of steps")?;
            calls += replay(instance, steps).map_err(|e| format!("{name}, trace {n}: {e}"))?;
            traces += 1;
        }
    }
    assert!(traces >= 30, "the fixtures are there: {traces} traces");
    assert!(calls >= traces, "every trace makes calls: {calls}");
    Ok(())
}
